### PR TITLE
Update wg_age_of_quic.md

### PR DESCRIPTION
**Pull request by jpcsmith**
Hey! I incorporated the feedback from #2 except for point 1. Do you have a suggestion for that point?

### CODE REVIEW

**Comment by JordanHolland** [comment]
Thanks! hopefully it was pretty easy. Did you optimize for `recall` or `r-precision` when training models?

**Comment by jpcsmith** [comment]
It depended on the model, as they were utilised as presented in the prior
work.

**Comment by JordanHolland** [comment]
2 leaderboards, each containing the models that were optimized for the metric associated with the leaderboard.

**Comment by jpcsmith** [comment]
When you have a moment, let's have a brief call.

**Comment by jpcsmith** [comment]
Updated with suggested changes.

**Pull request merged**
